/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface TechnicianResult {
    city: string;
    name: string;
    role: string;
    contactNumber: string;
}
export type Time = bigint;
export interface TechnicianSearchResult {
    otherCityMatches: Array<TechnicianResult>;
    sameCityMatches: Array<TechnicianResult>;
}
export interface TechnicianSearchInput {
    city: string;
    availableFrom: Time;
    requiredRoles: Array<string>;
    availableTo: Time;
}
export interface Director {
    yearsOfExperience: bigint;
    availabilityStart: Time;
    workReelUrl: string;
    fullName: string;
    currentCity: string;
    genreSpecialisation?: string;
    productSpecialisation?: string;
    availabilityEnd: Time;
    industryReference: string;
}
export interface UserProfile {
    yearsOfExperience: bigint;
    industryReferenceEmail: string;
    city: string;
    workReelUrl: string;
    designation: string;
    role: string;
    fullName: string;
    email: string;
    availability: Array<string>;
    tribeCompanyName: string;
    executiveProducers: Array<string>;
    contactNumber: string;
    department: string;
}
export enum TribalLeaderRole {
    director = "director",
    productionHouse = "productionHouse"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Create or update the caller's profile. Requires authenticated user.
     */
    createOrUpdateProfile(profile: UserProfile): Promise<void>;
    /**
     * / Get the caller's own profile (alias required by frontend). Requires authenticated user.
     */
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getDirectorRegistration(principal: Principal): Promise<Director | null>;
    /**
     * / Get the caller's own profile. Requires authenticated user.
     */
    getMyProfile(): Promise<UserProfile | null>;
    getTribalLeaderRole(principal: Principal): Promise<TribalLeaderRole | null>;
    /**
     * / Get a specific user's profile. Caller must be the owner or an admin.
     */
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / Save the caller's own profile (alias required by frontend). Requires authenticated user.
     */
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    /**
     * / Search for available technicians. No authentication required (public search).
     */
    searchTechnicians(searchInput: TechnicianSearchInput): Promise<TechnicianSearchResult>;
    submitDirectorRegistration(director: Director): Promise<void>;
    /**
     * / Submit a director registration using the full UserProfile model. Requires authenticated user.
     */
    submitDirectorRegistrationV2(director: UserProfile): Promise<void>;
    /**
     * / Submit a production house registration. Requires authenticated user.
     */
    submitProductionHouseRegistration(productionHouse: UserProfile): Promise<void>;
    /**
     * / Update only the availability field of the caller's profile. Requires authenticated user.
     */
    updateAvailability(availability: Array<string>): Promise<void>;
}
import type { Director as _Director, Time as _Time, TribalLeaderRole as _TribalLeaderRole, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getDirectorRegistration(arg0: Principal): Promise<Director | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getDirectorRegistration(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDirectorRegistration(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTribalLeaderRole(arg0: Principal): Promise<TribalLeaderRole | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTribalLeaderRole(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTribalLeaderRole(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async searchTechnicians(arg0: TechnicianSearchInput): Promise<TechnicianSearchResult> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTechnicians(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTechnicians(arg0);
            return result;
        }
    }
    async submitDirectorRegistration(arg0: Director): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDirectorRegistration(to_candid_Director_n13(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDirectorRegistration(to_candid_Director_n13(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitDirectorRegistrationV2(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitDirectorRegistrationV2(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitDirectorRegistrationV2(arg0);
            return result;
        }
    }
    async submitProductionHouseRegistration(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitProductionHouseRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitProductionHouseRegistration(arg0);
            return result;
        }
    }
    async updateAvailability(arg0: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAvailability(arg0);
            return result;
        }
    }
}
function from_candid_Director_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Director): Director {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TribalLeaderRole_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TribalLeaderRole): TribalLeaderRole {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_TribalLeaderRole]): TribalLeaderRole | null {
    return value.length === 0 ? null : from_candid_TribalLeaderRole_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Director]): Director | null {
    return value.length === 0 ? null : from_candid_Director_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    yearsOfExperience: bigint;
    availabilityStart: _Time;
    workReelUrl: string;
    fullName: string;
    currentCity: string;
    genreSpecialisation: [] | [string];
    productSpecialisation: [] | [string];
    availabilityEnd: _Time;
    industryReference: string;
}): {
    yearsOfExperience: bigint;
    availabilityStart: Time;
    workReelUrl: string;
    fullName: string;
    currentCity: string;
    genreSpecialisation?: string;
    productSpecialisation?: string;
    availabilityEnd: Time;
    industryReference: string;
} {
    return {
        yearsOfExperience: value.yearsOfExperience,
        availabilityStart: value.availabilityStart,
        workReelUrl: value.workReelUrl,
        fullName: value.fullName,
        currentCity: value.currentCity,
        genreSpecialisation: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.genreSpecialisation)),
        productSpecialisation: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.productSpecialisation)),
        availabilityEnd: value.availabilityEnd,
        industryReference: value.industryReference
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    director: null;
} | {
    productionHouse: null;
}): TribalLeaderRole {
    return "director" in value ? TribalLeaderRole.director : "productionHouse" in value ? TribalLeaderRole.productionHouse : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_Director_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Director): _Director {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    yearsOfExperience: bigint;
    availabilityStart: Time;
    workReelUrl: string;
    fullName: string;
    currentCity: string;
    genreSpecialisation?: string;
    productSpecialisation?: string;
    availabilityEnd: Time;
    industryReference: string;
}): {
    yearsOfExperience: bigint;
    availabilityStart: _Time;
    workReelUrl: string;
    fullName: string;
    currentCity: string;
    genreSpecialisation: [] | [string];
    productSpecialisation: [] | [string];
    availabilityEnd: _Time;
    industryReference: string;
} {
    return {
        yearsOfExperience: value.yearsOfExperience,
        availabilityStart: value.availabilityStart,
        workReelUrl: value.workReelUrl,
        fullName: value.fullName,
        currentCity: value.currentCity,
        genreSpecialisation: value.genreSpecialisation ? candid_some(value.genreSpecialisation) : candid_none(),
        productSpecialisation: value.productSpecialisation ? candid_some(value.productSpecialisation) : candid_none(),
        availabilityEnd: value.availabilityEnd,
        industryReference: value.industryReference
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
