/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface AdvertisingRegistration {
    yearsOfExperience: bigint;
    principal: Principal;
    areaOfExpertise: AreaOfExpertise;
    professionalDesignation: ProfessionalDesignation;
    workReelURL: string;
    name: string;
    currentCity: string;
    availability: Array<Time>;
    industryReferences?: string;
}
export type Time = bigint;
export interface UserProfile {
    areaOfExpertise?: AreaOfExpertise;
    professionalDesignation?: ProfessionalDesignation;
    name: string;
    currentCity: string;
}
export enum AreaOfExpertise {
    pr = "pr",
    media = "media",
    creative = "creative",
    production = "production",
    other = "other",
    research = "research",
    strategy = "strategy",
    postProduction = "postProduction",
    digital = "digital",
    accountManagement = "accountManagement"
}
export enum ProfessionalDesignation {
    other = "other",
    editor = "editor",
    artDirector = "artDirector",
    director = "director",
    designer = "designer",
    mediaPlanner = "mediaPlanner",
    accountExecutive = "accountExecutive",
    producer = "producer",
    cinematographer = "cinematographer",
    strategist = "strategist",
    copywriter = "copywriter"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getProfessionalRegistration(user: Principal): Promise<AdvertisingRegistration | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getVerifiedMembers(): Promise<Array<Principal>>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    submitProfessionalRegistration(registration: AdvertisingRegistration): Promise<void>;
}
import type { AdvertisingRegistration as _AdvertisingRegistration, AreaOfExpertise as _AreaOfExpertise, ProfessionalDesignation as _ProfessionalDesignation, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfessionalRegistration(arg0: Principal): Promise<AdvertisingRegistration | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfessionalRegistration(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfessionalRegistration(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getVerifiedMembers(): Promise<Array<Principal>> {
        if (this.processError) {
            try {
                const result = await this.actor.getVerifiedMembers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVerifiedMembers();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n18(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n18(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async submitProfessionalRegistration(arg0: AdvertisingRegistration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitProfessionalRegistration(to_candid_AdvertisingRegistration_n24(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitProfessionalRegistration(to_candid_AdvertisingRegistration_n24(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_AdvertisingRegistration_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdvertisingRegistration): AdvertisingRegistration {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_AreaOfExpertise_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AreaOfExpertise): AreaOfExpertise {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_ProfessionalDesignation_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProfessionalDesignation): ProfessionalDesignation {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdvertisingRegistration]): AdvertisingRegistration | null {
    return value.length === 0 ? null : from_candid_AdvertisingRegistration_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n4(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AreaOfExpertise]): AreaOfExpertise | null {
    return value.length === 0 ? null : from_candid_AreaOfExpertise_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProfessionalDesignation]): ProfessionalDesignation | null {
    return value.length === 0 ? null : from_candid_ProfessionalDesignation_n10(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    yearsOfExperience: bigint;
    principal: Principal;
    areaOfExpertise: _AreaOfExpertise;
    professionalDesignation: _ProfessionalDesignation;
    workReelURL: string;
    name: string;
    currentCity: string;
    availability: Array<_Time>;
    industryReferences: [] | [string];
}): {
    yearsOfExperience: bigint;
    principal: Principal;
    areaOfExpertise: AreaOfExpertise;
    professionalDesignation: ProfessionalDesignation;
    workReelURL: string;
    name: string;
    currentCity: string;
    availability: Array<Time>;
    industryReferences?: string;
} {
    return {
        yearsOfExperience: value.yearsOfExperience,
        principal: value.principal,
        areaOfExpertise: from_candid_AreaOfExpertise_n7(_uploadFile, _downloadFile, value.areaOfExpertise),
        professionalDesignation: from_candid_ProfessionalDesignation_n10(_uploadFile, _downloadFile, value.professionalDesignation),
        workReelURL: value.workReelURL,
        name: value.name,
        currentCity: value.currentCity,
        availability: value.availability,
        industryReferences: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.industryReferences))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    areaOfExpertise: [] | [_AreaOfExpertise];
    professionalDesignation: [] | [_ProfessionalDesignation];
    name: string;
    currentCity: string;
}): {
    areaOfExpertise?: AreaOfExpertise;
    professionalDesignation?: ProfessionalDesignation;
    name: string;
    currentCity: string;
} {
    return {
        areaOfExpertise: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.areaOfExpertise)),
        professionalDesignation: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.professionalDesignation)),
        name: value.name,
        currentCity: value.currentCity
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    editor: null;
} | {
    artDirector: null;
} | {
    director: null;
} | {
    designer: null;
} | {
    mediaPlanner: null;
} | {
    accountExecutive: null;
} | {
    producer: null;
} | {
    cinematographer: null;
} | {
    strategist: null;
} | {
    copywriter: null;
}): ProfessionalDesignation {
    return "other" in value ? ProfessionalDesignation.other : "editor" in value ? ProfessionalDesignation.editor : "artDirector" in value ? ProfessionalDesignation.artDirector : "director" in value ? ProfessionalDesignation.director : "designer" in value ? ProfessionalDesignation.designer : "mediaPlanner" in value ? ProfessionalDesignation.mediaPlanner : "accountExecutive" in value ? ProfessionalDesignation.accountExecutive : "producer" in value ? ProfessionalDesignation.producer : "cinematographer" in value ? ProfessionalDesignation.cinematographer : "strategist" in value ? ProfessionalDesignation.strategist : "copywriter" in value ? ProfessionalDesignation.copywriter : value;
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pr: null;
} | {
    media: null;
} | {
    creative: null;
} | {
    production: null;
} | {
    other: null;
} | {
    research: null;
} | {
    strategy: null;
} | {
    postProduction: null;
} | {
    digital: null;
} | {
    accountManagement: null;
}): AreaOfExpertise {
    return "pr" in value ? AreaOfExpertise.pr : "media" in value ? AreaOfExpertise.media : "creative" in value ? AreaOfExpertise.creative : "production" in value ? AreaOfExpertise.production : "other" in value ? AreaOfExpertise.other : "research" in value ? AreaOfExpertise.research : "strategy" in value ? AreaOfExpertise.strategy : "postProduction" in value ? AreaOfExpertise.postProduction : "digital" in value ? AreaOfExpertise.digital : "accountManagement" in value ? AreaOfExpertise.accountManagement : value;
}
function to_candid_AdvertisingRegistration_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdvertisingRegistration): _AdvertisingRegistration {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_AreaOfExpertise_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AreaOfExpertise): _AreaOfExpertise {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_ProfessionalDesignation_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfessionalDesignation): _ProfessionalDesignation {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n19(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    areaOfExpertise?: AreaOfExpertise;
    professionalDesignation?: ProfessionalDesignation;
    name: string;
    currentCity: string;
}): {
    areaOfExpertise: [] | [_AreaOfExpertise];
    professionalDesignation: [] | [_ProfessionalDesignation];
    name: string;
    currentCity: string;
} {
    return {
        areaOfExpertise: value.areaOfExpertise ? candid_some(to_candid_AreaOfExpertise_n20(_uploadFile, _downloadFile, value.areaOfExpertise)) : candid_none(),
        professionalDesignation: value.professionalDesignation ? candid_some(to_candid_ProfessionalDesignation_n22(_uploadFile, _downloadFile, value.professionalDesignation)) : candid_none(),
        name: value.name,
        currentCity: value.currentCity
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    yearsOfExperience: bigint;
    principal: Principal;
    areaOfExpertise: AreaOfExpertise;
    professionalDesignation: ProfessionalDesignation;
    workReelURL: string;
    name: string;
    currentCity: string;
    availability: Array<Time>;
    industryReferences?: string;
}): {
    yearsOfExperience: bigint;
    principal: Principal;
    areaOfExpertise: _AreaOfExpertise;
    professionalDesignation: _ProfessionalDesignation;
    workReelURL: string;
    name: string;
    currentCity: string;
    availability: Array<_Time>;
    industryReferences: [] | [string];
} {
    return {
        yearsOfExperience: value.yearsOfExperience,
        principal: value.principal,
        areaOfExpertise: to_candid_AreaOfExpertise_n20(_uploadFile, _downloadFile, value.areaOfExpertise),
        professionalDesignation: to_candid_ProfessionalDesignation_n22(_uploadFile, _downloadFile, value.professionalDesignation),
        workReelURL: value.workReelURL,
        name: value.name,
        currentCity: value.currentCity,
        availability: value.availability,
        industryReferences: value.industryReferences ? candid_some(value.industryReferences) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AreaOfExpertise): {
    pr: null;
} | {
    media: null;
} | {
    creative: null;
} | {
    production: null;
} | {
    other: null;
} | {
    research: null;
} | {
    strategy: null;
} | {
    postProduction: null;
} | {
    digital: null;
} | {
    accountManagement: null;
} {
    return value == AreaOfExpertise.pr ? {
        pr: null
    } : value == AreaOfExpertise.media ? {
        media: null
    } : value == AreaOfExpertise.creative ? {
        creative: null
    } : value == AreaOfExpertise.production ? {
        production: null
    } : value == AreaOfExpertise.other ? {
        other: null
    } : value == AreaOfExpertise.research ? {
        research: null
    } : value == AreaOfExpertise.strategy ? {
        strategy: null
    } : value == AreaOfExpertise.postProduction ? {
        postProduction: null
    } : value == AreaOfExpertise.digital ? {
        digital: null
    } : value == AreaOfExpertise.accountManagement ? {
        accountManagement: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProfessionalDesignation): {
    other: null;
} | {
    editor: null;
} | {
    artDirector: null;
} | {
    director: null;
} | {
    designer: null;
} | {
    mediaPlanner: null;
} | {
    accountExecutive: null;
} | {
    producer: null;
} | {
    cinematographer: null;
} | {
    strategist: null;
} | {
    copywriter: null;
} {
    return value == ProfessionalDesignation.other ? {
        other: null
    } : value == ProfessionalDesignation.editor ? {
        editor: null
    } : value == ProfessionalDesignation.artDirector ? {
        artDirector: null
    } : value == ProfessionalDesignation.director ? {
        director: null
    } : value == ProfessionalDesignation.designer ? {
        designer: null
    } : value == ProfessionalDesignation.mediaPlanner ? {
        mediaPlanner: null
    } : value == ProfessionalDesignation.accountExecutive ? {
        accountExecutive: null
    } : value == ProfessionalDesignation.producer ? {
        producer: null
    } : value == ProfessionalDesignation.cinematographer ? {
        cinematographer: null
    } : value == ProfessionalDesignation.strategist ? {
        strategist: null
    } : value == ProfessionalDesignation.copywriter ? {
        copywriter: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
