/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface EquipmentVendor {
    id: Principal;
    inventory: Array<string>;
    name: string;
    availability: Array<CalendarAvailability>;
}
export interface CalendarAvailability {
    status: Variant_booked_available_unavailable;
    date: Time;
}
export type Time = bigint;
export interface ShootLocation {
    id: Principal;
    name: string;
    description: string;
    pricing: bigint;
    availability: Array<CalendarAvailability>;
    capacity: bigint;
}
export interface ProductionHouse {
    id: Principal;
    name: string;
    verifiedConnections: Array<Principal>;
    companyInfo: string;
}
export interface UserProfile {
    name: string;
    profileType: Variant_professional_vendor_productionHouse_location;
}
export interface AdvertisingProfessional {
    id: Principal;
    portfolio: Array<string>;
    name: string;
    availability: Array<CalendarAvailability>;
    specialties: Array<string>;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_booked_available_unavailable {
    booked = "booked",
    available = "available",
    unavailable = "unavailable"
}
export enum Variant_professional_vendor_productionHouse_location {
    professional = "professional",
    vendor = "vendor",
    productionHouse = "productionHouse",
    location = "location"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    acceptRecommendation(recommendationFrom: Principal): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    declineRecommendation(recommendationFrom: Principal): Promise<void>;
    getAdvertisingProfessional(id: Principal): Promise<AdvertisingProfessional>;
    getAllAdvertisingProfessionals(): Promise<Array<AdvertisingProfessional>>;
    getAllCategories(): Promise<Array<string>>;
    getAllEquipmentVendors(): Promise<Array<EquipmentVendor>>;
    getAllProductionHouses(): Promise<Array<ProductionHouse>>;
    getAllProfessions(): Promise<Array<string>>;
    getAllShootLocations(): Promise<Array<ShootLocation>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getEquipmentVendor(id: Principal): Promise<EquipmentVendor>;
    getShootLocation(id: Principal): Promise<ShootLocation>;
    getTimeSlotEntries(date: Time): Promise<{
        professionals: Array<AdvertisingProfessional>;
        vendors: Array<EquipmentVendor>;
        locations: Array<ShootLocation>;
    }>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchAdvertisingProfessionalsBySpecialty(specialty: string): Promise<Array<AdvertisingProfessional>>;
    searchEquipmentVendorsByInventory(item: string): Promise<Array<EquipmentVendor>>;
    searchShootLocationsByCapacity(requiredCapacity: bigint): Promise<Array<ShootLocation>>;
    sendRecommendation(toUser: Principal, message: string): Promise<void>;
    setAdvertisingProfessional(professional: AdvertisingProfessional): Promise<void>;
    setEquipmentVendor(vendor: EquipmentVendor): Promise<void>;
    setProductionHouse(house: ProductionHouse): Promise<void>;
    setShootLocation(location: ShootLocation): Promise<void>;
    updateAvailability(id: Principal, availability: Array<CalendarAvailability>): Promise<void>;
}
import type { AdvertisingProfessional as _AdvertisingProfessional, CalendarAvailability as _CalendarAvailability, EquipmentVendor as _EquipmentVendor, ShootLocation as _ShootLocation, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async acceptRecommendation(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptRecommendation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptRecommendation(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async declineRecommendation(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.declineRecommendation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.declineRecommendation(arg0);
            return result;
        }
    }
    async getAdvertisingProfessional(arg0: Principal): Promise<AdvertisingProfessional> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdvertisingProfessional(arg0);
                return from_candid_AdvertisingProfessional_n3(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdvertisingProfessional(arg0);
            return from_candid_AdvertisingProfessional_n3(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllAdvertisingProfessionals(): Promise<Array<AdvertisingProfessional>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllAdvertisingProfessionals();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllAdvertisingProfessionals();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCategories(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return result;
        }
    }
    async getAllEquipmentVendors(): Promise<Array<EquipmentVendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEquipmentVendors();
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEquipmentVendors();
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProductionHouses(): Promise<Array<ProductionHouse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProductionHouses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProductionHouses();
            return result;
        }
    }
    async getAllProfessions(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProfessions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProfessions();
            return result;
        }
    }
    async getAllShootLocations(): Promise<Array<ShootLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllShootLocations();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllShootLocations();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEquipmentVendor(arg0: Principal): Promise<EquipmentVendor> {
        if (this.processError) {
            try {
                const result = await this.actor.getEquipmentVendor(arg0);
                return from_candid_EquipmentVendor_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEquipmentVendor(arg0);
            return from_candid_EquipmentVendor_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getShootLocation(arg0: Principal): Promise<ShootLocation> {
        if (this.processError) {
            try {
                const result = await this.actor.getShootLocation(arg0);
                return from_candid_ShootLocation_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getShootLocation(arg0);
            return from_candid_ShootLocation_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTimeSlotEntries(arg0: Time): Promise<{
        professionals: Array<AdvertisingProfessional>;
        vendors: Array<EquipmentVendor>;
        locations: Array<ShootLocation>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getTimeSlotEntries(arg0);
                return from_candid_record_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTimeSlotEntries(arg0);
            return from_candid_record_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n23(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n23(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchAdvertisingProfessionalsBySpecialty(arg0: string): Promise<Array<AdvertisingProfessional>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAdvertisingProfessionalsBySpecialty(arg0);
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAdvertisingProfessionalsBySpecialty(arg0);
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchEquipmentVendorsByInventory(arg0: string): Promise<Array<EquipmentVendor>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchEquipmentVendorsByInventory(arg0);
                return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchEquipmentVendorsByInventory(arg0);
            return from_candid_vec_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchShootLocationsByCapacity(arg0: bigint): Promise<Array<ShootLocation>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchShootLocationsByCapacity(arg0);
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchShootLocationsByCapacity(arg0);
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendRecommendation(arg0: Principal, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendRecommendation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendRecommendation(arg0, arg1);
            return result;
        }
    }
    async setAdvertisingProfessional(arg0: AdvertisingProfessional): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAdvertisingProfessional(to_candid_AdvertisingProfessional_n26(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAdvertisingProfessional(to_candid_AdvertisingProfessional_n26(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setEquipmentVendor(arg0: EquipmentVendor): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setEquipmentVendor(to_candid_EquipmentVendor_n32(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setEquipmentVendor(to_candid_EquipmentVendor_n32(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setProductionHouse(arg0: ProductionHouse): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setProductionHouse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setProductionHouse(arg0);
            return result;
        }
    }
    async setShootLocation(arg0: ShootLocation): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setShootLocation(to_candid_ShootLocation_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setShootLocation(to_candid_ShootLocation_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateAvailability(arg0: Principal, arg1: Array<CalendarAvailability>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAvailability(arg0, to_candid_vec_n28(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAvailability(arg0, to_candid_vec_n28(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_AdvertisingProfessional_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AdvertisingProfessional): AdvertisingProfessional {
    return from_candid_record_n4(_uploadFile, _downloadFile, value);
}
function from_candid_CalendarAvailability_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CalendarAvailability): CalendarAvailability {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_EquipmentVendor_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EquipmentVendor): EquipmentVendor {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_ShootLocation_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ShootLocation): ShootLocation {
    return from_candid_record_n15(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    inventory: Array<string>;
    name: string;
    availability: Array<_CalendarAvailability>;
}): {
    id: Principal;
    inventory: Array<string>;
    name: string;
    availability: Array<CalendarAvailability>;
} {
    return {
        id: value.id,
        inventory: value.inventory,
        name: value.name,
        availability: from_candid_vec_n5(_uploadFile, _downloadFile, value.availability)
    };
}
function from_candid_record_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    description: string;
    pricing: bigint;
    availability: Array<_CalendarAvailability>;
    capacity: bigint;
}): {
    id: Principal;
    name: string;
    description: string;
    pricing: bigint;
    availability: Array<CalendarAvailability>;
    capacity: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        pricing: value.pricing,
        availability: from_candid_vec_n5(_uploadFile, _downloadFile, value.availability),
        capacity: value.capacity
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    profileType: {
        professional: null;
    } | {
        vendor: null;
    } | {
        productionHouse: null;
    } | {
        location: null;
    };
}): {
    name: string;
    profileType: Variant_professional_vendor_productionHouse_location;
} {
    return {
        name: value.name,
        profileType: from_candid_variant_n19(_uploadFile, _downloadFile, value.profileType)
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    professionals: Array<_AdvertisingProfessional>;
    vendors: Array<_EquipmentVendor>;
    locations: Array<_ShootLocation>;
}): {
    professionals: Array<AdvertisingProfessional>;
    vendors: Array<EquipmentVendor>;
    locations: Array<ShootLocation>;
} {
    return {
        professionals: from_candid_vec_n9(_uploadFile, _downloadFile, value.professionals),
        vendors: from_candid_vec_n10(_uploadFile, _downloadFile, value.vendors),
        locations: from_candid_vec_n13(_uploadFile, _downloadFile, value.locations)
    };
}
function from_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    portfolio: Array<string>;
    name: string;
    availability: Array<_CalendarAvailability>;
    specialties: Array<string>;
}): {
    id: Principal;
    portfolio: Array<string>;
    name: string;
    availability: Array<CalendarAvailability>;
    specialties: Array<string>;
} {
    return {
        id: value.id,
        portfolio: value.portfolio,
        name: value.name,
        availability: from_candid_vec_n5(_uploadFile, _downloadFile, value.availability),
        specialties: value.specialties
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        booked: null;
    } | {
        available: null;
    } | {
        unavailable: null;
    };
    date: _Time;
}): {
    status: Variant_booked_available_unavailable;
    date: Time;
} {
    return {
        status: from_candid_variant_n8(_uploadFile, _downloadFile, value.status),
        date: value.date
    };
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    professional: null;
} | {
    vendor: null;
} | {
    productionHouse: null;
} | {
    location: null;
}): Variant_professional_vendor_productionHouse_location {
    return "professional" in value ? Variant_professional_vendor_productionHouse_location.professional : "vendor" in value ? Variant_professional_vendor_productionHouse_location.vendor : "productionHouse" in value ? Variant_professional_vendor_productionHouse_location.productionHouse : "location" in value ? Variant_professional_vendor_productionHouse_location.location : value;
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    booked: null;
} | {
    available: null;
} | {
    unavailable: null;
}): Variant_booked_available_unavailable {
    return "booked" in value ? Variant_booked_available_unavailable.booked : "available" in value ? Variant_booked_available_unavailable.available : "unavailable" in value ? Variant_booked_available_unavailable.unavailable : value;
}
function from_candid_vec_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EquipmentVendor>): Array<EquipmentVendor> {
    return value.map((x)=>from_candid_EquipmentVendor_n11(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ShootLocation>): Array<ShootLocation> {
    return value.map((x)=>from_candid_ShootLocation_n14(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CalendarAvailability>): Array<CalendarAvailability> {
    return value.map((x)=>from_candid_CalendarAvailability_n6(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AdvertisingProfessional>): Array<AdvertisingProfessional> {
    return value.map((x)=>from_candid_AdvertisingProfessional_n3(_uploadFile, _downloadFile, x));
}
function to_candid_AdvertisingProfessional_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AdvertisingProfessional): _AdvertisingProfessional {
    return to_candid_record_n27(_uploadFile, _downloadFile, value);
}
function to_candid_CalendarAvailability_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CalendarAvailability): _CalendarAvailability {
    return to_candid_record_n30(_uploadFile, _downloadFile, value);
}
function to_candid_EquipmentVendor_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EquipmentVendor): _EquipmentVendor {
    return to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_ShootLocation_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ShootLocation): _ShootLocation {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n24(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    profileType: Variant_professional_vendor_productionHouse_location;
}): {
    name: string;
    profileType: {
        professional: null;
    } | {
        vendor: null;
    } | {
        productionHouse: null;
    } | {
        location: null;
    };
} {
    return {
        name: value.name,
        profileType: to_candid_variant_n25(_uploadFile, _downloadFile, value.profileType)
    };
}
function to_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    portfolio: Array<string>;
    name: string;
    availability: Array<CalendarAvailability>;
    specialties: Array<string>;
}): {
    id: Principal;
    portfolio: Array<string>;
    name: string;
    availability: Array<_CalendarAvailability>;
    specialties: Array<string>;
} {
    return {
        id: value.id,
        portfolio: value.portfolio,
        name: value.name,
        availability: to_candid_vec_n28(_uploadFile, _downloadFile, value.availability),
        specialties: value.specialties
    };
}
function to_candid_record_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: Variant_booked_available_unavailable;
    date: Time;
}): {
    status: {
        booked: null;
    } | {
        available: null;
    } | {
        unavailable: null;
    };
    date: _Time;
} {
    return {
        status: to_candid_variant_n31(_uploadFile, _downloadFile, value.status),
        date: value.date
    };
}
function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    inventory: Array<string>;
    name: string;
    availability: Array<CalendarAvailability>;
}): {
    id: Principal;
    inventory: Array<string>;
    name: string;
    availability: Array<_CalendarAvailability>;
} {
    return {
        id: value.id,
        inventory: value.inventory,
        name: value.name,
        availability: to_candid_vec_n28(_uploadFile, _downloadFile, value.availability)
    };
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    name: string;
    description: string;
    pricing: bigint;
    availability: Array<CalendarAvailability>;
    capacity: bigint;
}): {
    id: Principal;
    name: string;
    description: string;
    pricing: bigint;
    availability: Array<_CalendarAvailability>;
    capacity: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        pricing: value.pricing,
        availability: to_candid_vec_n28(_uploadFile, _downloadFile, value.availability),
        capacity: value.capacity
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_professional_vendor_productionHouse_location): {
    professional: null;
} | {
    vendor: null;
} | {
    productionHouse: null;
} | {
    location: null;
} {
    return value == Variant_professional_vendor_productionHouse_location.professional ? {
        professional: null
    } : value == Variant_professional_vendor_productionHouse_location.vendor ? {
        vendor: null
    } : value == Variant_professional_vendor_productionHouse_location.productionHouse ? {
        productionHouse: null
    } : value == Variant_professional_vendor_productionHouse_location.location ? {
        location: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_booked_available_unavailable): {
    booked: null;
} | {
    available: null;
} | {
    unavailable: null;
} {
    return value == Variant_booked_available_unavailable.booked ? {
        booked: null
    } : value == Variant_booked_available_unavailable.available ? {
        available: null
    } : value == Variant_booked_available_unavailable.unavailable ? {
        unavailable: null
    } : value;
}
function to_candid_vec_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CalendarAvailability>): Array<_CalendarAvailability> {
    return value.map((x)=>to_candid_CalendarAvailability_n29(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
