/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'yearsOfExperience' : IDL.Nat,
  'industryReferenceEmail' : IDL.Text,
  'city' : IDL.Text,
  'workReelUrl' : IDL.Text,
  'designation' : IDL.Text,
  'role' : IDL.Text,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'availability' : IDL.Vec(IDL.Text),
  'tribeCompanyName' : IDL.Text,
  'executiveProducers' : IDL.Vec(IDL.Text),
  'contactNumber' : IDL.Text,
  'department' : IDL.Text,
});
export const Time = IDL.Int;
export const Director = IDL.Record({
  'yearsOfExperience' : IDL.Nat,
  'availabilityStart' : Time,
  'workReelUrl' : IDL.Text,
  'fullName' : IDL.Text,
  'currentCity' : IDL.Text,
  'genreSpecialisation' : IDL.Opt(IDL.Text),
  'productSpecialisation' : IDL.Opt(IDL.Text),
  'availabilityEnd' : Time,
  'industryReference' : IDL.Text,
});
export const TribalLeaderRole = IDL.Variant({
  'director' : IDL.Null,
  'productionHouse' : IDL.Null,
});
export const TechnicianSearchInput = IDL.Record({
  'city' : IDL.Text,
  'availableFrom' : Time,
  'requiredRoles' : IDL.Vec(IDL.Text),
  'availableTo' : Time,
});
export const TechnicianResult = IDL.Record({
  'city' : IDL.Text,
  'name' : IDL.Text,
  'role' : IDL.Text,
  'contactNumber' : IDL.Text,
});
export const TechnicianSearchResult = IDL.Record({
  'otherCityMatches' : IDL.Vec(TechnicianResult),
  'sameCityMatches' : IDL.Vec(TechnicianResult),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDirectorRegistration' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(Director)],
      ['query'],
    ),
  'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getTribalLeaderRole' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(TribalLeaderRole)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTechnicians' : IDL.Func(
      [TechnicianSearchInput],
      [TechnicianSearchResult],
      ['query'],
    ),
  'submitDirectorRegistration' : IDL.Func([Director], [], []),
  'submitDirectorRegistrationV2' : IDL.Func([UserProfile], [], []),
  'submitProductionHouseRegistration' : IDL.Func([UserProfile], [], []),
  'updateAvailability' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'yearsOfExperience' : IDL.Nat,
    'industryReferenceEmail' : IDL.Text,
    'city' : IDL.Text,
    'workReelUrl' : IDL.Text,
    'designation' : IDL.Text,
    'role' : IDL.Text,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'availability' : IDL.Vec(IDL.Text),
    'tribeCompanyName' : IDL.Text,
    'executiveProducers' : IDL.Vec(IDL.Text),
    'contactNumber' : IDL.Text,
    'department' : IDL.Text,
  });
  const Time = IDL.Int;
  const Director = IDL.Record({
    'yearsOfExperience' : IDL.Nat,
    'availabilityStart' : Time,
    'workReelUrl' : IDL.Text,
    'fullName' : IDL.Text,
    'currentCity' : IDL.Text,
    'genreSpecialisation' : IDL.Opt(IDL.Text),
    'productSpecialisation' : IDL.Opt(IDL.Text),
    'availabilityEnd' : Time,
    'industryReference' : IDL.Text,
  });
  const TribalLeaderRole = IDL.Variant({
    'director' : IDL.Null,
    'productionHouse' : IDL.Null,
  });
  const TechnicianSearchInput = IDL.Record({
    'city' : IDL.Text,
    'availableFrom' : Time,
    'requiredRoles' : IDL.Vec(IDL.Text),
    'availableTo' : Time,
  });
  const TechnicianResult = IDL.Record({
    'city' : IDL.Text,
    'name' : IDL.Text,
    'role' : IDL.Text,
    'contactNumber' : IDL.Text,
  });
  const TechnicianSearchResult = IDL.Record({
    'otherCityMatches' : IDL.Vec(TechnicianResult),
    'sameCityMatches' : IDL.Vec(TechnicianResult),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDirectorRegistration' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(Director)],
        ['query'],
      ),
    'getMyProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getTribalLeaderRole' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(TribalLeaderRole)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTechnicians' : IDL.Func(
        [TechnicianSearchInput],
        [TechnicianSearchResult],
        ['query'],
      ),
    'submitDirectorRegistration' : IDL.Func([Director], [], []),
    'submitDirectorRegistrationV2' : IDL.Func([UserProfile], [], []),
    'submitProductionHouseRegistration' : IDL.Func([UserProfile], [], []),
    'updateAvailability' : IDL.Func([IDL.Vec(IDL.Text)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };