/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const AreaOfExpertise = IDL.Variant({
  'pr' : IDL.Null,
  'media' : IDL.Null,
  'creative' : IDL.Null,
  'production' : IDL.Null,
  'other' : IDL.Null,
  'research' : IDL.Null,
  'strategy' : IDL.Null,
  'postProduction' : IDL.Null,
  'digital' : IDL.Null,
  'accountManagement' : IDL.Null,
});
export const ProfessionalDesignation = IDL.Variant({
  'other' : IDL.Null,
  'editor' : IDL.Null,
  'artDirector' : IDL.Null,
  'director' : IDL.Null,
  'designer' : IDL.Null,
  'mediaPlanner' : IDL.Null,
  'accountExecutive' : IDL.Null,
  'producer' : IDL.Null,
  'cinematographer' : IDL.Null,
  'strategist' : IDL.Null,
  'copywriter' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'areaOfExpertise' : IDL.Opt(AreaOfExpertise),
  'professionalDesignation' : IDL.Opt(ProfessionalDesignation),
  'name' : IDL.Text,
  'currentCity' : IDL.Text,
});
export const Time = IDL.Int;
export const AdvertisingRegistration = IDL.Record({
  'yearsOfExperience' : IDL.Nat,
  'principal' : IDL.Principal,
  'areaOfExpertise' : AreaOfExpertise,
  'professionalDesignation' : ProfessionalDesignation,
  'workReelURL' : IDL.Text,
  'name' : IDL.Text,
  'currentCity' : IDL.Text,
  'availability' : IDL.Vec(Time),
  'industryReferences' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfessionalRegistration' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(AdvertisingRegistration)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVerifiedMembers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitProfessionalRegistration' : IDL.Func(
      [AdvertisingRegistration],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const AreaOfExpertise = IDL.Variant({
    'pr' : IDL.Null,
    'media' : IDL.Null,
    'creative' : IDL.Null,
    'production' : IDL.Null,
    'other' : IDL.Null,
    'research' : IDL.Null,
    'strategy' : IDL.Null,
    'postProduction' : IDL.Null,
    'digital' : IDL.Null,
    'accountManagement' : IDL.Null,
  });
  const ProfessionalDesignation = IDL.Variant({
    'other' : IDL.Null,
    'editor' : IDL.Null,
    'artDirector' : IDL.Null,
    'director' : IDL.Null,
    'designer' : IDL.Null,
    'mediaPlanner' : IDL.Null,
    'accountExecutive' : IDL.Null,
    'producer' : IDL.Null,
    'cinematographer' : IDL.Null,
    'strategist' : IDL.Null,
    'copywriter' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'areaOfExpertise' : IDL.Opt(AreaOfExpertise),
    'professionalDesignation' : IDL.Opt(ProfessionalDesignation),
    'name' : IDL.Text,
    'currentCity' : IDL.Text,
  });
  const Time = IDL.Int;
  const AdvertisingRegistration = IDL.Record({
    'yearsOfExperience' : IDL.Nat,
    'principal' : IDL.Principal,
    'areaOfExpertise' : AreaOfExpertise,
    'professionalDesignation' : ProfessionalDesignation,
    'workReelURL' : IDL.Text,
    'name' : IDL.Text,
    'currentCity' : IDL.Text,
    'availability' : IDL.Vec(Time),
    'industryReferences' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfessionalRegistration' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(AdvertisingRegistration)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVerifiedMembers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitProfessionalRegistration' : IDL.Func(
        [AdvertisingRegistration],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };