/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdvertisingRegistration {
  'yearsOfExperience' : bigint,
  'principal' : Principal,
  'areaOfExpertise' : AreaOfExpertise,
  'professionalDesignation' : ProfessionalDesignation,
  'workReelURL' : string,
  'name' : string,
  'currentCity' : string,
  'availability' : Array<Time>,
  'industryReferences' : [] | [string],
}
export type AreaOfExpertise = { 'pr' : null } |
  { 'media' : null } |
  { 'creative' : null } |
  { 'production' : null } |
  { 'other' : null } |
  { 'research' : null } |
  { 'strategy' : null } |
  { 'postProduction' : null } |
  { 'digital' : null } |
  { 'accountManagement' : null };
export type ProfessionalDesignation = { 'other' : null } |
  { 'editor' : null } |
  { 'artDirector' : null } |
  { 'director' : null } |
  { 'designer' : null } |
  { 'mediaPlanner' : null } |
  { 'accountExecutive' : null } |
  { 'producer' : null } |
  { 'cinematographer' : null } |
  { 'strategist' : null } |
  { 'copywriter' : null };
export type Time = bigint;
export interface UserProfile {
  'areaOfExpertise' : [] | [AreaOfExpertise],
  'professionalDesignation' : [] | [ProfessionalDesignation],
  'name' : string,
  'currentCity' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProfessionalRegistration' : ActorMethod<
    [Principal],
    [] | [AdvertisingRegistration]
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVerifiedMembers' : ActorMethod<[], Array<Principal>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitProfessionalRegistration' : ActorMethod<
    [AdvertisingRegistration],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];