/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdvertisingProfessional {
  'id' : Principal,
  'portfolio' : Array<string>,
  'name' : string,
  'availability' : Array<CalendarAvailability>,
  'specialties' : Array<string>,
}
export interface CalendarAvailability {
  'status' : { 'booked' : null } |
    { 'available' : null } |
    { 'unavailable' : null },
  'date' : Time,
}
export interface EquipmentVendor {
  'id' : Principal,
  'inventory' : Array<string>,
  'name' : string,
  'availability' : Array<CalendarAvailability>,
}
export interface ProductionHouse {
  'id' : Principal,
  'name' : string,
  'verifiedConnections' : Array<Principal>,
  'companyInfo' : string,
}
export interface ShootLocation {
  'id' : Principal,
  'name' : string,
  'description' : string,
  'pricing' : bigint,
  'availability' : Array<CalendarAvailability>,
  'capacity' : bigint,
}
export type Time = bigint;
export interface UserProfile {
  'name' : string,
  'profileType' : { 'professional' : null } |
    { 'vendor' : null } |
    { 'productionHouse' : null } |
    { 'location' : null },
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'acceptRecommendation' : ActorMethod<[Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'declineRecommendation' : ActorMethod<[Principal], undefined>,
  'getAdvertisingProfessional' : ActorMethod<
    [Principal],
    AdvertisingProfessional
  >,
  'getAllAdvertisingProfessionals' : ActorMethod<
    [],
    Array<AdvertisingProfessional>
  >,
  'getAllCategories' : ActorMethod<[], Array<string>>,
  'getAllEquipmentVendors' : ActorMethod<[], Array<EquipmentVendor>>,
  'getAllProductionHouses' : ActorMethod<[], Array<ProductionHouse>>,
  'getAllProfessions' : ActorMethod<[], Array<string>>,
  'getAllShootLocations' : ActorMethod<[], Array<ShootLocation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEquipmentVendor' : ActorMethod<[Principal], EquipmentVendor>,
  'getShootLocation' : ActorMethod<[Principal], ShootLocation>,
  'getTimeSlotEntries' : ActorMethod<
    [Time],
    {
      'professionals' : Array<AdvertisingProfessional>,
      'vendors' : Array<EquipmentVendor>,
      'locations' : Array<ShootLocation>,
    }
  >,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchAdvertisingProfessionalsBySpecialty' : ActorMethod<
    [string],
    Array<AdvertisingProfessional>
  >,
  'searchEquipmentVendorsByInventory' : ActorMethod<
    [string],
    Array<EquipmentVendor>
  >,
  'searchShootLocationsByCapacity' : ActorMethod<
    [bigint],
    Array<ShootLocation>
  >,
  'sendRecommendation' : ActorMethod<[Principal, string], undefined>,
  'setAdvertisingProfessional' : ActorMethod<
    [AdvertisingProfessional],
    undefined
  >,
  'setEquipmentVendor' : ActorMethod<[EquipmentVendor], undefined>,
  'setProductionHouse' : ActorMethod<[ProductionHouse], undefined>,
  'setShootLocation' : ActorMethod<[ShootLocation], undefined>,
  'updateAvailability' : ActorMethod<
    [Principal, Array<CalendarAvailability>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];