/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Director {
  'yearsOfExperience' : bigint,
  'availabilityStart' : Time,
  'workReelUrl' : string,
  'fullName' : string,
  'currentCity' : string,
  'genreSpecialisation' : [] | [string],
  'productSpecialisation' : [] | [string],
  'availabilityEnd' : Time,
  'industryReference' : string,
}
export interface TechnicianResult {
  'city' : string,
  'name' : string,
  'role' : string,
  'contactNumber' : string,
}
export interface TechnicianSearchInput {
  'city' : string,
  'availableFrom' : Time,
  'requiredRoles' : Array<string>,
  'availableTo' : Time,
}
export interface TechnicianSearchResult {
  'otherCityMatches' : Array<TechnicianResult>,
  'sameCityMatches' : Array<TechnicianResult>,
}
export type Time = bigint;
export type TribalLeaderRole = { 'director' : null } |
  { 'productionHouse' : null };
export interface UserProfile {
  'yearsOfExperience' : bigint,
  'industryReferenceEmail' : string,
  'city' : string,
  'workReelUrl' : string,
  'designation' : string,
  'role' : string,
  'fullName' : string,
  'email' : string,
  'availability' : Array<string>,
  'tribeCompanyName' : string,
  'executiveProducers' : Array<string>,
  'contactNumber' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Create or update the caller's profile. Requires authenticated user.
   */
  'createOrUpdateProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Get the caller's own profile (alias required by frontend). Requires authenticated user.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDirectorRegistration' : ActorMethod<[Principal], [] | [Director]>,
  /**
   * / Get the caller's own profile. Requires authenticated user.
   */
  'getMyProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getTribalLeaderRole' : ActorMethod<[Principal], [] | [TribalLeaderRole]>,
  /**
   * / Get a specific user's profile. Caller must be the owner or an admin.
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Save the caller's own profile (alias required by frontend). Requires authenticated user.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Search for available technicians. No authentication required (public search).
   */
  'searchTechnicians' : ActorMethod<
    [TechnicianSearchInput],
    TechnicianSearchResult
  >,
  'submitDirectorRegistration' : ActorMethod<[Director], undefined>,
  /**
   * / Submit a director registration using the full UserProfile model. Requires authenticated user.
   */
  'submitDirectorRegistrationV2' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Submit a production house registration. Requires authenticated user.
   */
  'submitProductionHouseRegistration' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Update only the availability field of the caller's profile. Requires authenticated user.
   */
  'updateAvailability' : ActorMethod<[Array<string>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];