/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const CalendarAvailability = IDL.Record({
  'status' : IDL.Variant({
    'booked' : IDL.Null,
    'available' : IDL.Null,
    'unavailable' : IDL.Null,
  }),
  'date' : Time,
});
export const AdvertisingProfessional = IDL.Record({
  'id' : IDL.Principal,
  'portfolio' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'availability' : IDL.Vec(CalendarAvailability),
  'specialties' : IDL.Vec(IDL.Text),
});
export const EquipmentVendor = IDL.Record({
  'id' : IDL.Principal,
  'inventory' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'availability' : IDL.Vec(CalendarAvailability),
});
export const ProductionHouse = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'verifiedConnections' : IDL.Vec(IDL.Principal),
  'companyInfo' : IDL.Text,
});
export const ShootLocation = IDL.Record({
  'id' : IDL.Principal,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'pricing' : IDL.Nat,
  'availability' : IDL.Vec(CalendarAvailability),
  'capacity' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'profileType' : IDL.Variant({
    'professional' : IDL.Null,
    'vendor' : IDL.Null,
    'productionHouse' : IDL.Null,
    'location' : IDL.Null,
  }),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptRecommendation' : IDL.Func([IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'declineRecommendation' : IDL.Func([IDL.Principal], [], []),
  'getAdvertisingProfessional' : IDL.Func(
      [IDL.Principal],
      [AdvertisingProfessional],
      ['query'],
    ),
  'getAllAdvertisingProfessionals' : IDL.Func(
      [],
      [IDL.Vec(AdvertisingProfessional)],
      ['query'],
    ),
  'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllEquipmentVendors' : IDL.Func(
      [],
      [IDL.Vec(EquipmentVendor)],
      ['query'],
    ),
  'getAllProductionHouses' : IDL.Func(
      [],
      [IDL.Vec(ProductionHouse)],
      ['query'],
    ),
  'getAllProfessions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getAllShootLocations' : IDL.Func([], [IDL.Vec(ShootLocation)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEquipmentVendor' : IDL.Func(
      [IDL.Principal],
      [EquipmentVendor],
      ['query'],
    ),
  'getShootLocation' : IDL.Func([IDL.Principal], [ShootLocation], ['query']),
  'getTimeSlotEntries' : IDL.Func(
      [Time],
      [
        IDL.Record({
          'professionals' : IDL.Vec(AdvertisingProfessional),
          'vendors' : IDL.Vec(EquipmentVendor),
          'locations' : IDL.Vec(ShootLocation),
        }),
      ],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchAdvertisingProfessionalsBySpecialty' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AdvertisingProfessional)],
      ['query'],
    ),
  'searchEquipmentVendorsByInventory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(EquipmentVendor)],
      ['query'],
    ),
  'searchShootLocationsByCapacity' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(ShootLocation)],
      ['query'],
    ),
  'sendRecommendation' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'setAdvertisingProfessional' : IDL.Func([AdvertisingProfessional], [], []),
  'setEquipmentVendor' : IDL.Func([EquipmentVendor], [], []),
  'setProductionHouse' : IDL.Func([ProductionHouse], [], []),
  'setShootLocation' : IDL.Func([ShootLocation], [], []),
  'updateAvailability' : IDL.Func(
      [IDL.Principal, IDL.Vec(CalendarAvailability)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const CalendarAvailability = IDL.Record({
    'status' : IDL.Variant({
      'booked' : IDL.Null,
      'available' : IDL.Null,
      'unavailable' : IDL.Null,
    }),
    'date' : Time,
  });
  const AdvertisingProfessional = IDL.Record({
    'id' : IDL.Principal,
    'portfolio' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'availability' : IDL.Vec(CalendarAvailability),
    'specialties' : IDL.Vec(IDL.Text),
  });
  const EquipmentVendor = IDL.Record({
    'id' : IDL.Principal,
    'inventory' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'availability' : IDL.Vec(CalendarAvailability),
  });
  const ProductionHouse = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'verifiedConnections' : IDL.Vec(IDL.Principal),
    'companyInfo' : IDL.Text,
  });
  const ShootLocation = IDL.Record({
    'id' : IDL.Principal,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'pricing' : IDL.Nat,
    'availability' : IDL.Vec(CalendarAvailability),
    'capacity' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'profileType' : IDL.Variant({
      'professional' : IDL.Null,
      'vendor' : IDL.Null,
      'productionHouse' : IDL.Null,
      'location' : IDL.Null,
    }),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptRecommendation' : IDL.Func([IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'declineRecommendation' : IDL.Func([IDL.Principal], [], []),
    'getAdvertisingProfessional' : IDL.Func(
        [IDL.Principal],
        [AdvertisingProfessional],
        ['query'],
      ),
    'getAllAdvertisingProfessionals' : IDL.Func(
        [],
        [IDL.Vec(AdvertisingProfessional)],
        ['query'],
      ),
    'getAllCategories' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllEquipmentVendors' : IDL.Func(
        [],
        [IDL.Vec(EquipmentVendor)],
        ['query'],
      ),
    'getAllProductionHouses' : IDL.Func(
        [],
        [IDL.Vec(ProductionHouse)],
        ['query'],
      ),
    'getAllProfessions' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getAllShootLocations' : IDL.Func([], [IDL.Vec(ShootLocation)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEquipmentVendor' : IDL.Func(
        [IDL.Principal],
        [EquipmentVendor],
        ['query'],
      ),
    'getShootLocation' : IDL.Func([IDL.Principal], [ShootLocation], ['query']),
    'getTimeSlotEntries' : IDL.Func(
        [Time],
        [
          IDL.Record({
            'professionals' : IDL.Vec(AdvertisingProfessional),
            'vendors' : IDL.Vec(EquipmentVendor),
            'locations' : IDL.Vec(ShootLocation),
          }),
        ],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchAdvertisingProfessionalsBySpecialty' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AdvertisingProfessional)],
        ['query'],
      ),
    'searchEquipmentVendorsByInventory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(EquipmentVendor)],
        ['query'],
      ),
    'searchShootLocationsByCapacity' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ShootLocation)],
        ['query'],
      ),
    'sendRecommendation' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'setAdvertisingProfessional' : IDL.Func([AdvertisingProfessional], [], []),
    'setEquipmentVendor' : IDL.Func([EquipmentVendor], [], []),
    'setProductionHouse' : IDL.Func([ProductionHouse], [], []),
    'setShootLocation' : IDL.Func([ShootLocation], [], []),
    'updateAvailability' : IDL.Func(
        [IDL.Principal, IDL.Vec(CalendarAvailability)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };